### ISSUE TITLE
Get the interest rate data for modeling 

### ISSUE THREAD

**Issue by andrewkroening** [andrewkroening/Math789_Project#4]

**Comment by jeremymtan** [comment]
We can just use Nick's dataset for this: 
https://home.treasury.gov/resource-center/data-chart-center/interest-rates/TextView?type=daily_treasury_real_yield_curve&field_tdr_date_value_month=202309

Or use this alternative on that tracks Federal Reserve interset rates:
https://www.kaggle.com/datasets/federalreserve/interest-rates/data

If we want to use a bank's interest rates over time (such as CITI) we would need to scrape their website to get accuate data which might take too much time to follow something like this:
https://www.kaggle.com/datasets/samuelcortinhas/bank-of-england-interest-rates-19752021

**Comment by andrewkroening** [comment]
> We can just use Nick's dataset for this: https://home.treasury.gov/resource-center/data-chart-center/interest-rates/TextView?type=daily_treasury_real_yield_curve&field_tdr_date_value_month=202309

I built a dataset from this site and will push it back to the main branch shortly. 2010-2023, real daily interest rates. Which brings the question, which one of these are we predicting? Or all of them??

**Comment by andrewkroening** [comment]
> I looked at Nick's notebook, and he predicts one month and 30 year interest rates for "Daily Treasury Par Yield Curve Rates", but our data is somewhat different. I think we would need to formulate a research question and decide what we want to do.

Can you add his notebook to a branch and merge it. Just throw it in the code directory. I don't have access to it. Just want to take a look.

**Comment by jeremymtan** [comment]
I made a new branch to "nick_build" and just copied the project over to the code folder
