### ISSUE TITLE
Research Modeling Techniques

### ISSUE THREAD

**Issue by andrewkroening** [andrewkroening/Math789_Project#5]

**Comment by jeremymtan** [comment]
- Linear Regression 
   - simplest model
   - would need other features to train on if we use this, and also assume a linear relationship between our outcome and predictor variables 
- Support Vector Regression 
   - more complex, doesn't assume linear relationship 
- Deep Learning
   - use Nick's example and use MLPs 
   - try using LTSM and see the difference

**Comment by andrewkroening** [comment]
Deep learning is probably the best for default. There are different treatments we can apply to the dataset to try out.

I'm looking through these today:
- https://medium.com/fintechexplained/forecasting-interest-rates-short-rate-term-models-9c1902ed636d
- https://medium.com/fintechexplained/forecasting-interest-rates-mean-reverting-drift-term-structure-models-d8c92eb3cf6a

Other option I think could be cool to try is an Azure Auto ML model because those can get a little silly.

**Comment by jeremymtan** [comment]
I'm happy to try Azure Auto ML since we have azure credits right now from Professor Gift's class and as long as we don't waste too much in a single day I can ask Scott to increase the credits for me.

**Comment by andrewkroening** [comment]
> I'm happy to try Azure Auto ML since we have azure credits right now from Professor Gift's class and as long as we don't waste too much in a single day I can ask Scott to increase the credits for me.

Let's build the dataset first. I still gotta see how to get these tweets.

**Comment by andrewkroening** [comment]
I found a bunch of articles but can't seem to get the actual datasets. I'm gonna start on the MLP Regressor, you wanna start the AutoML Experiment?

**Comment by jeremymtan** [comment]
Sure, I have a lot of work due for classes today so not sure I can make much progress today but will have something to show by end of week.

**Comment by andrewkroening** [comment]
@jeremymtan Follow me here. But I think this is a cool idea. What if the rows are look backs, and the columns are look ahead ranges. Then we try to score models for each combination and answer what look back you need to reasonably predict going forward? We could also do for rounded interest rates...


**Sample Accuracy Matrix**

| | 1 Day | 7 Days | 30 Days | 90 Days |
| --- | --- | --- | --- | --- |
| **1 Day** | | | | |
| **7 Days** | | | | |
| **30 Days** | | | | |
| **90 Days** | | | | |

**Comment by jeremymtan** [comment]
Works for me, but I would probably need more clarification so we are on the same page later.
